/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_BMW_IVI_IVI_HPP_
#define V1_BMW_IVI_IVI_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace bmw {
namespace ivi {

class IVI {
public:
    virtual ~IVI() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct SignType : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            STOP_SIGN = 0,
            SPEED_LIMIT_SIGN = 1,
            ROAD_BLOCK_SIGN = 2
        };
    
        SignType()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::STOP_SIGN)) {}
        SignType(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::STOP_SIGN):
                case static_cast< uint8_t>(Literal::SPEED_LIMIT_SIGN):
                case static_cast< uint8_t>(Literal::ROAD_BLOCK_SIGN):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SignType &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SignType &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SignType &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SignType &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SignType &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SignType &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::STOP_SIGN): return "STOP_SIGN";
            case static_cast< uint8_t>(Literal::SPEED_LIMIT_SIGN): return "SPEED_LIMIT_SIGN";
            case static_cast< uint8_t>(Literal::ROAD_BLOCK_SIGN): return "ROAD_BLOCK_SIGN";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* IVI::getInterface() {
    return ("bmw.ivi.IVI:v1_0");
}

CommonAPI::Version IVI::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace ivi
} // namespace bmw
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_BMW_IVI_IVI_HPP_
