/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/bmw/ivi/IVISomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace bmw {
namespace ivi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createIVISomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< IVISomeIPProxy>(_address, _connection);
}

void initializeIVISomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:bmw.ivi.IVI:v1_0:bmw.ivi.IVI",
        0x1b1e, 0x567a, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "bmw.ivi.IVI:v1_0",
        &createIVISomeIPProxy);
}

INITIALIZER(registerIVISomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeIVISomeIPProxy);
}

IVISomeIPProxy::IVISomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          notifySpeedLimitSignDetected_(*this, 0x1b5a, CommonAPI::SomeIP::event_id_t(0x9476), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int16_t>* >(nullptr))),
          notifyStopSignDetected_(*this, 0x1b5a, CommonAPI::SomeIP::event_id_t(0x9477), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple()),
          notifyRoadBlockDetected_(*this, 0x1b5a, CommonAPI::SomeIP::event_id_t(0x9478), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple()),
          notifyIVICpuLoad_(*this, 0x1b5b, CommonAPI::SomeIP::event_id_t(0x9486), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
{
}

IVISomeIPProxy::~IVISomeIPProxy() {
}


IVISomeIPProxy::NotifySpeedLimitSignDetectedEvent& IVISomeIPProxy::getNotifySpeedLimitSignDetectedEvent() {
    return notifySpeedLimitSignDetected_;
}
IVISomeIPProxy::NotifyStopSignDetectedEvent& IVISomeIPProxy::getNotifyStopSignDetectedEvent() {
    return notifyStopSignDetected_;
}
IVISomeIPProxy::NotifyRoadBlockDetectedEvent& IVISomeIPProxy::getNotifyRoadBlockDetectedEvent() {
    return notifyRoadBlockDetected_;
}
IVISomeIPProxy::NotifyIVICpuLoadEvent& IVISomeIPProxy::getNotifyIVICpuLoadEvent() {
    return notifyIVICpuLoad_;
}

void IVISomeIPProxy::requestIVICpuLoad(CommonAPI::CallStatus &_internalCallStatus, float &_usage, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_usage(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3),
        true, // reliable = TCP
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_usage);
    _usage = deploy_usage.getValue();
}

std::future<CommonAPI::CallStatus> IVISomeIPProxy::requestIVICpuLoadAsync(RequestIVICpuLoadAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_usage(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x3),
        true, // reliable = TCP
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< float, CommonAPI::EmptyDeployment > _usage) {
            if (_callback)
                _callback(_internalCallStatus, _usage.getValue());
        },
        std::make_tuple(deploy_usage));
}

void IVISomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> IVISomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace ivi
} // namespace bmw
} // namespace v1
