/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_BMW_IVI_IVI_STUB_HPP_
#define V1_BMW_IVI_IVI_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/bmw/ivi/IVI.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace bmw {
namespace ivi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service IVI. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class IVIStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual IVI {
 public:
    /**
    * Sends a broadcast event for notifySpeedLimitSignDetected. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireNotifySpeedLimitSignDetectedEvent(const int16_t &_speedLimit) = 0;
    /**
    * Sends a broadcast event for notifyStopSignDetected. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireNotifyStopSignDetectedEvent() = 0;
    /**
    * Sends a broadcast event for notifyRoadBlockDetected. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireNotifyRoadBlockDetectedEvent() = 0;
    /**
    * Sends a broadcast event for notifyIVICpuLoad. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireNotifyIVICpuLoadEvent(const float &_usage) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for IVI.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class IVIStubRemoteEvent
{
public:
    virtual ~IVIStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service IVI to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class IVIStub
    : public virtual CommonAPI::Stub<IVIStubAdapter, IVIStubRemoteEvent>
{
public:
    typedef std::function<void (float _usage)> requestIVICpuLoadReply_t;

    virtual ~IVIStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 5);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Sends a broadcast event for notifySpeedLimitSignDetected.
    virtual void fireNotifySpeedLimitSignDetectedEvent(const int16_t &_speedLimit) {
        auto stubAdapter = CommonAPI::Stub<IVIStubAdapter, IVIStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireNotifySpeedLimitSignDetectedEvent(_speedLimit);
    }
    /// Sends a broadcast event for notifyStopSignDetected.
    virtual void fireNotifyStopSignDetectedEvent() {
        auto stubAdapter = CommonAPI::Stub<IVIStubAdapter, IVIStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireNotifyStopSignDetectedEvent();
    }
    /// Sends a broadcast event for notifyRoadBlockDetected.
    virtual void fireNotifyRoadBlockDetectedEvent() {
        auto stubAdapter = CommonAPI::Stub<IVIStubAdapter, IVIStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireNotifyRoadBlockDetectedEvent();
    }
    /// Sends a broadcast event for notifyIVICpuLoad.
    virtual void fireNotifyIVICpuLoadEvent(const float &_usage) {
        auto stubAdapter = CommonAPI::Stub<IVIStubAdapter, IVIStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireNotifyIVICpuLoadEvent(_usage);
    }
    /// This is the method that will be called on remote calls on the method requestIVICpuLoad.
    virtual void requestIVICpuLoad(const std::shared_ptr<CommonAPI::ClientId> _client, requestIVICpuLoadReply_t _reply) = 0;


    using CommonAPI::Stub<IVIStubAdapter, IVIStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<IVIStubAdapter, IVIStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<IVIStubAdapter, IVIStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef IVIStubRemoteEvent RemoteEventType;
    typedef ::v1::bmw::ivi::IVI StubInterface;
};

} // namespace ivi
} // namespace bmw
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_BMW_IVI_IVI_STUB_HPP_
